### ISSUE TITLE
Calls to updateStatus() can trigger a WDT timeout

### ISSUE THREAD

**Issue by marclefevre** [dushyantahuja/SimpleWeather#1]
I'm using your library on an ESP8266 project.  I'm using the OpenWeatherMap class and I find that when I call updateStatus(), I get a WDT (exception 29) about half of the time.  The times that no WDT timeout occurs, take about 8 seconds for the call to complete.

Do you call delay() or yield() periodically in these methods?

Do you have a non-blocking interface that I could use?

Thanks for the simple library.

**Comment by dushyantahuja** [comment]
The code is pretty simple, and there aren't any delays or yields. As a matter of fact, there aren't any loops as such either. My guess is that the openweathermap website is taking too long to respond. 
Do you want to try darksky instead - I think that's faster.

I'm not sure how I can make this non-blocking.
