### ISSUE TITLE
Hardcoded dependency on ESP8266WiFi.h

### ISSUE THREAD

**Issue by asciipip** [dushyantahuja/SimpleWeather#2]
The `#include <ESP8266WiFi.h>` in both `SimpleWeather.h` and `SimpleWeather.cpp` prevents compilation on any other platform, even otherwise-compatible ones like the ESP32.  It would probably be better to replace that `#include` statement with this:

    #if defined(ESP8266)
      #include <ESP8266WiFi.h>
    #elif defined(ESP32)
      #include <WiFi.h>
    #endif

**Comment by dushyantahuja** [comment]
Hi Phil, I have not used ESP32 till now. Is this the only change required, or other changes will also be needed to support and ESP32?

**Comment by dushyantahuja** [comment]
I've made the change - let me know if it still doesn't work for ESP32

**Comment by asciipip** [comment]
I've just verified with the current code; it now works fine on my ESP32.  Thanks!
